//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smsCoreLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EFREN RAFANAN")]
        public string rUbo7SbaeKZQuaCKmF {
            get {
                return ((string)(this["rUbo7SbaeKZQuaCKmF"]));
            }
            set {
                this["rUbo7SbaeKZQuaCKmF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LITE-DISTRIBUTION")]
        public string C7sjZ9SZ6BQmFMTuFx {
            get {
                return ((string)(this["C7sjZ9SZ6BQmFMTuFx"]));
            }
            set {
                this["C7sjZ9SZ6BQmFMTuFx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MWGC-Y4PN-G5K6-BP3F")]
        public string fCoBhMKoYAWRCwhoB {
            get {
                return ((string)(this["fCoBhMKoYAWRCwhoB"]));
            }
            set {
                this["fCoBhMKoYAWRCwhoB"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:4711/smsLauncherManagement/service/license.asmx")]
        public string smsCoreLib_smslicense_license {
            get {
                return ((string)(this["smsCoreLib_smslicense_license"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lCompany {
            get {
                return ((string)(this["lCompany"]));
            }
            set {
                this["lCompany"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lType {
            get {
                return ((string)(this["lType"]));
            }
            set {
                this["lType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lKey {
            get {
                return ((string)(this["lKey"]));
            }
            set {
                this["lKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsActivated {
            get {
                return ((bool)(this["IsActivated"]));
            }
            set {
                this["IsActivated"] = value;
            }
        }
    }
}
