#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smsLauncher.model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SMSDatabase")]
	public partial class SMSDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSMS_Inbox(SMS_Inbox instance);
    partial void UpdateSMS_Inbox(SMS_Inbox instance);
    partial void DeleteSMS_Inbox(SMS_Inbox instance);
    partial void InsertSMS_QueuedBox(SMS_QueuedBox instance);
    partial void UpdateSMS_QueuedBox(SMS_QueuedBox instance);
    partial void DeleteSMS_QueuedBox(SMS_QueuedBox instance);
    partial void InsertSMS_SentItem(SMS_SentItem instance);
    partial void UpdateSMS_SentItem(SMS_SentItem instance);
    partial void DeleteSMS_SentItem(SMS_SentItem instance);
    partial void InsertSMS_ReceivedMsg(SMS_ReceivedMsg instance);
    partial void UpdateSMS_ReceivedMsg(SMS_ReceivedMsg instance);
    partial void DeleteSMS_ReceivedMsg(SMS_ReceivedMsg instance);
    partial void InsertSMS_Cache(SMS_Cache instance);
    partial void UpdateSMS_Cache(SMS_Cache instance);
    partial void DeleteSMS_Cache(SMS_Cache instance);
    partial void InsertSMS_ActivationCode(SMS_ActivationCode instance);
    partial void UpdateSMS_ActivationCode(SMS_ActivationCode instance);
    partial void DeleteSMS_ActivationCode(SMS_ActivationCode instance);
    partial void InsertSMS_Member(SMS_Member instance);
    partial void UpdateSMS_Member(SMS_Member instance);
    partial void DeleteSMS_Member(SMS_Member instance);
    partial void InsertSMS_Reply(SMS_Reply instance);
    partial void UpdateSMS_Reply(SMS_Reply instance);
    partial void DeleteSMS_Reply(SMS_Reply instance);
    partial void InsertSMS_TransferFundReport(SMS_TransferFundReport instance);
    partial void UpdateSMS_TransferFundReport(SMS_TransferFundReport instance);
    partial void DeleteSMS_TransferFundReport(SMS_TransferFundReport instance);
    partial void InsertSMS_eMoney(SMS_eMoney instance);
    partial void UpdateSMS_eMoney(SMS_eMoney instance);
    partial void DeleteSMS_eMoney(SMS_eMoney instance);
    partial void InsertSMS_WeatherForecast(SMS_WeatherForecast instance);
    partial void UpdateSMS_WeatherForecast(SMS_WeatherForecast instance);
    partial void DeleteSMS_WeatherForecast(SMS_WeatherForecast instance);
    partial void InsertSMS_BayanihanSum(SMS_BayanihanSum instance);
    partial void UpdateSMS_BayanihanSum(SMS_BayanihanSum instance);
    partial void DeleteSMS_BayanihanSum(SMS_BayanihanSum instance);
    partial void InsertSMS_Bayanihan(SMS_Bayanihan instance);
    partial void UpdateSMS_Bayanihan(SMS_Bayanihan instance);
    partial void DeleteSMS_Bayanihan(SMS_Bayanihan instance);
    #endregion
		
		public SMSDataClassesDataContext() : 
				base(global::smsLauncher.Properties.Settings.Default.SMSDatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SMSDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMSDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMSDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMSDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SMS_Inbox> SMS_Inboxes
		{
			get
			{
				return this.GetTable<SMS_Inbox>();
			}
		}
		
		public System.Data.Linq.Table<SMS_QueuedBox> SMS_QueuedBoxes
		{
			get
			{
				return this.GetTable<SMS_QueuedBox>();
			}
		}
		
		public System.Data.Linq.Table<SMS_SentItem> SMS_SentItems
		{
			get
			{
				return this.GetTable<SMS_SentItem>();
			}
		}
		
		public System.Data.Linq.Table<SMS_ReceivedMsg> SMS_ReceivedMsgs
		{
			get
			{
				return this.GetTable<SMS_ReceivedMsg>();
			}
		}
		
		public System.Data.Linq.Table<SMS_Cache> SMS_Caches
		{
			get
			{
				return this.GetTable<SMS_Cache>();
			}
		}
		
		public System.Data.Linq.Table<SMS_ActivationCode> SMS_ActivationCodes
		{
			get
			{
				return this.GetTable<SMS_ActivationCode>();
			}
		}
		
		public System.Data.Linq.Table<SMS_Member> SMS_Members
		{
			get
			{
				return this.GetTable<SMS_Member>();
			}
		}
		
		public System.Data.Linq.Table<SMS_Reply> SMS_Replies
		{
			get
			{
				return this.GetTable<SMS_Reply>();
			}
		}
		
		public System.Data.Linq.Table<SMS_TransferFundReport> SMS_TransferFundReports
		{
			get
			{
				return this.GetTable<SMS_TransferFundReport>();
			}
		}
		
		public System.Data.Linq.Table<SMS_eMoney> SMS_eMoneys
		{
			get
			{
				return this.GetTable<SMS_eMoney>();
			}
		}
		
		public System.Data.Linq.Table<SMS_WeatherForecast> SMS_WeatherForecasts
		{
			get
			{
				return this.GetTable<SMS_WeatherForecast>();
			}
		}
		
		public System.Data.Linq.Table<SMS_BayanihanSum> SMS_BayanihanSums
		{
			get
			{
				return this.GetTable<SMS_BayanihanSum>();
			}
		}
		
		public System.Data.Linq.Table<SMS_Bayanihan> SMS_Bayanihans
		{
			get
			{
				return this.GetTable<SMS_Bayanihan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SMS_Inbox")]
	public partial class SMS_Inbox : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Sender;
		
		private string _Message;
		
		private System.Nullable<System.DateTime> _DateReceived;
		
		private System.Nullable<int> _MonthOf;
		
		private System.Nullable<long> _YearOf;
		
		private System.Nullable<bool> _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnSenderChanging(string value);
    partial void OnSenderChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnDateReceivedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateReceivedChanged();
    partial void OnMonthOfChanging(System.Nullable<int> value);
    partial void OnMonthOfChanged();
    partial void OnYearOfChanging(System.Nullable<long> value);
    partial void OnYearOfChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public SMS_Inbox()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sender", DbType="VarChar(13)")]
		public string Sender
		{
			get
			{
				return this._Sender;
			}
			set
			{
				if ((this._Sender != value))
				{
					this.OnSenderChanging(value);
					this.SendPropertyChanging();
					this._Sender = value;
					this.SendPropertyChanged("Sender");
					this.OnSenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(200)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReceived", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateReceived
		{
			get
			{
				return this._DateReceived;
			}
			set
			{
				if ((this._DateReceived != value))
				{
					this.OnDateReceivedChanging(value);
					this.SendPropertyChanging();
					this._DateReceived = value;
					this.SendPropertyChanged("DateReceived");
					this.OnDateReceivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthOf", DbType="Int")]
		public System.Nullable<int> MonthOf
		{
			get
			{
				return this._MonthOf;
			}
			set
			{
				if ((this._MonthOf != value))
				{
					this.OnMonthOfChanging(value);
					this.SendPropertyChanging();
					this._MonthOf = value;
					this.SendPropertyChanged("MonthOf");
					this.OnMonthOfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearOf", DbType="BigInt")]
		public System.Nullable<long> YearOf
		{
			get
			{
				return this._YearOf;
			}
			set
			{
				if ((this._YearOf != value))
				{
					this.OnYearOfChanging(value);
					this.SendPropertyChanging();
					this._YearOf = value;
					this.SendPropertyChanged("YearOf");
					this.OnYearOfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SMS_QueuedBox")]
	public partial class SMS_QueuedBox : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Number;
		
		private string _Message;
		
		private System.Nullable<short> _Network;
		
		private System.Nullable<bool> _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNumberChanging(string value);
    partial void OnNumberChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnNetworkChanging(System.Nullable<short> value);
    partial void OnNetworkChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public SMS_QueuedBox()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="VarChar(11)")]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(MAX)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Network", DbType="SmallInt")]
		public System.Nullable<short> Network
		{
			get
			{
				return this._Network;
			}
			set
			{
				if ((this._Network != value))
				{
					this.OnNetworkChanging(value);
					this.SendPropertyChanging();
					this._Network = value;
					this.SendPropertyChanged("Network");
					this.OnNetworkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SMS_SentItems")]
	public partial class SMS_SentItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Number;
		
		private string _Message;
		
		private System.Nullable<System.DateTime> _DateTime;
		
		private System.Nullable<bool> _Status;
		
		private System.Nullable<int> _MonthOf;
		
		private System.Nullable<long> _YearOf;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNumberChanging(string value);
    partial void OnNumberChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnDateTimeChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnMonthOfChanging(System.Nullable<int> value);
    partial void OnMonthOfChanged();
    partial void OnYearOfChanging(System.Nullable<long> value);
    partial void OnYearOfChanged();
    #endregion
		
		public SMS_SentItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="VarChar(11)")]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(MAX)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthOf", DbType="Int")]
		public System.Nullable<int> MonthOf
		{
			get
			{
				return this._MonthOf;
			}
			set
			{
				if ((this._MonthOf != value))
				{
					this.OnMonthOfChanging(value);
					this.SendPropertyChanging();
					this._MonthOf = value;
					this.SendPropertyChanged("MonthOf");
					this.OnMonthOfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearOf", DbType="BigInt")]
		public System.Nullable<long> YearOf
		{
			get
			{
				return this._YearOf;
			}
			set
			{
				if ((this._YearOf != value))
				{
					this.OnYearOfChanging(value);
					this.SendPropertyChanging();
					this._YearOf = value;
					this.SendPropertyChanged("YearOf");
					this.OnYearOfChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SMS_ReceivedMsg")]
	public partial class SMS_ReceivedMsg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Sender;
		
		private string _Message;
		
		private System.Nullable<System.DateTime> _DateReceived;
		
		private System.Nullable<int> _MonthOf;
		
		private System.Nullable<long> _YearOf;
		
		private System.Nullable<bool> _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnSenderChanging(string value);
    partial void OnSenderChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnDateReceivedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateReceivedChanged();
    partial void OnMonthOfChanging(System.Nullable<int> value);
    partial void OnMonthOfChanged();
    partial void OnYearOfChanging(System.Nullable<long> value);
    partial void OnYearOfChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public SMS_ReceivedMsg()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sender", DbType="VarChar(13)")]
		public string Sender
		{
			get
			{
				return this._Sender;
			}
			set
			{
				if ((this._Sender != value))
				{
					this.OnSenderChanging(value);
					this.SendPropertyChanging();
					this._Sender = value;
					this.SendPropertyChanged("Sender");
					this.OnSenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(200)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReceived", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateReceived
		{
			get
			{
				return this._DateReceived;
			}
			set
			{
				if ((this._DateReceived != value))
				{
					this.OnDateReceivedChanging(value);
					this.SendPropertyChanging();
					this._DateReceived = value;
					this.SendPropertyChanged("DateReceived");
					this.OnDateReceivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthOf", DbType="Int")]
		public System.Nullable<int> MonthOf
		{
			get
			{
				return this._MonthOf;
			}
			set
			{
				if ((this._MonthOf != value))
				{
					this.OnMonthOfChanging(value);
					this.SendPropertyChanging();
					this._MonthOf = value;
					this.SendPropertyChanged("MonthOf");
					this.OnMonthOfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearOf", DbType="BigInt")]
		public System.Nullable<long> YearOf
		{
			get
			{
				return this._YearOf;
			}
			set
			{
				if ((this._YearOf != value))
				{
					this.OnYearOfChanging(value);
					this.SendPropertyChanging();
					this._YearOf = value;
					this.SendPropertyChanged("YearOf");
					this.OnYearOfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SMS_Cache")]
	public partial class SMS_Cache : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Number;
		
		private string _Message;
		
		private System.Nullable<bool> _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNumberChanging(string value);
    partial void OnNumberChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public SMS_Cache()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="VarChar(11)")]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(200)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SMS_ActivationCode")]
	public partial class SMS_ActivationCode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _PINCode;
		
		private bool _Status;
		
		private string _SerialNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnPINCodeChanging(string value);
    partial void OnPINCodeChanged();
    partial void OnStatusChanging(bool value);
    partial void OnStatusChanged();
    partial void OnSerialNoChanging(string value);
    partial void OnSerialNoChanged();
    #endregion
		
		public SMS_ActivationCode()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PINCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PINCode
		{
			get
			{
				return this._PINCode;
			}
			set
			{
				if ((this._PINCode != value))
				{
					this.OnPINCodeChanging(value);
					this.SendPropertyChanging();
					this._PINCode = value;
					this.SendPropertyChanged("PINCode");
					this.OnPINCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNo", DbType="VarChar(20)")]
		public string SerialNo
		{
			get
			{
				return this._SerialNo;
			}
			set
			{
				if ((this._SerialNo != value))
				{
					this.OnSerialNoChanging(value);
					this.SendPropertyChanging();
					this._SerialNo = value;
					this.SendPropertyChanged("SerialNo");
					this.OnSerialNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SMS_Members")]
	public partial class SMS_Member : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _ReferenceNo;
		
		private string _Group_Name;
		
		private string _Account_Number;
		
		private string _Family_Name;
		
		private string _First_Name;
		
		private string _Town;
		
		private string _Province;
		
		private string _Sponsor_ID;
		
		private string _CP_Number;
		
		private System.Nullable<short> _Section_A;
		
		private System.Nullable<short> _Section_B;
		
		private string _Pin_Code;
		
		private System.Nullable<System.DateTime> _DateReg;
		
		private System.Nullable<bool> _Status;
		
		private System.Nullable<int> _monthOf;
		
		private System.Nullable<long> _yearOf;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnReferenceNoChanging(string value);
    partial void OnReferenceNoChanged();
    partial void OnGroup_NameChanging(string value);
    partial void OnGroup_NameChanged();
    partial void OnAccount_NumberChanging(string value);
    partial void OnAccount_NumberChanged();
    partial void OnFamily_NameChanging(string value);
    partial void OnFamily_NameChanged();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnTownChanging(string value);
    partial void OnTownChanged();
    partial void OnProvinceChanging(string value);
    partial void OnProvinceChanged();
    partial void OnSponsor_IDChanging(string value);
    partial void OnSponsor_IDChanged();
    partial void OnCP_NumberChanging(string value);
    partial void OnCP_NumberChanged();
    partial void OnSection_AChanging(System.Nullable<short> value);
    partial void OnSection_AChanged();
    partial void OnSection_BChanging(System.Nullable<short> value);
    partial void OnSection_BChanged();
    partial void OnPin_CodeChanging(string value);
    partial void OnPin_CodeChanged();
    partial void OnDateRegChanging(System.Nullable<System.DateTime> value);
    partial void OnDateRegChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnmonthOfChanging(System.Nullable<int> value);
    partial void OnmonthOfChanged();
    partial void OnyearOfChanging(System.Nullable<long> value);
    partial void OnyearOfChanged();
    #endregion
		
		public SMS_Member()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceNo", DbType="VarChar(MAX)")]
		public string ReferenceNo
		{
			get
			{
				return this._ReferenceNo;
			}
			set
			{
				if ((this._ReferenceNo != value))
				{
					this.OnReferenceNoChanging(value);
					this.SendPropertyChanging();
					this._ReferenceNo = value;
					this.SendPropertyChanged("ReferenceNo");
					this.OnReferenceNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group_Name", DbType="VarChar(100)")]
		public string Group_Name
		{
			get
			{
				return this._Group_Name;
			}
			set
			{
				if ((this._Group_Name != value))
				{
					this.OnGroup_NameChanging(value);
					this.SendPropertyChanging();
					this._Group_Name = value;
					this.SendPropertyChanged("Group_Name");
					this.OnGroup_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account_Number", DbType="VarChar(14)")]
		public string Account_Number
		{
			get
			{
				return this._Account_Number;
			}
			set
			{
				if ((this._Account_Number != value))
				{
					this.OnAccount_NumberChanging(value);
					this.SendPropertyChanging();
					this._Account_Number = value;
					this.SendPropertyChanged("Account_Number");
					this.OnAccount_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Family_Name", DbType="VarChar(50)")]
		public string Family_Name
		{
			get
			{
				return this._Family_Name;
			}
			set
			{
				if ((this._Family_Name != value))
				{
					this.OnFamily_NameChanging(value);
					this.SendPropertyChanging();
					this._Family_Name = value;
					this.SendPropertyChanged("Family_Name");
					this.OnFamily_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="VarChar(50)")]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this.OnFirst_NameChanging(value);
					this.SendPropertyChanging();
					this._First_Name = value;
					this.SendPropertyChanged("First_Name");
					this.OnFirst_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Town", DbType="VarChar(50)")]
		public string Town
		{
			get
			{
				return this._Town;
			}
			set
			{
				if ((this._Town != value))
				{
					this.OnTownChanging(value);
					this.SendPropertyChanging();
					this._Town = value;
					this.SendPropertyChanged("Town");
					this.OnTownChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="VarChar(50)")]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this.OnProvinceChanging(value);
					this.SendPropertyChanging();
					this._Province = value;
					this.SendPropertyChanged("Province");
					this.OnProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sponsor_ID", DbType="VarChar(11)")]
		public string Sponsor_ID
		{
			get
			{
				return this._Sponsor_ID;
			}
			set
			{
				if ((this._Sponsor_ID != value))
				{
					this.OnSponsor_IDChanging(value);
					this.SendPropertyChanging();
					this._Sponsor_ID = value;
					this.SendPropertyChanged("Sponsor_ID");
					this.OnSponsor_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CP_Number", DbType="VarChar(11)")]
		public string CP_Number
		{
			get
			{
				return this._CP_Number;
			}
			set
			{
				if ((this._CP_Number != value))
				{
					this.OnCP_NumberChanging(value);
					this.SendPropertyChanging();
					this._CP_Number = value;
					this.SendPropertyChanged("CP_Number");
					this.OnCP_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_A", DbType="SmallInt")]
		public System.Nullable<short> Section_A
		{
			get
			{
				return this._Section_A;
			}
			set
			{
				if ((this._Section_A != value))
				{
					this.OnSection_AChanging(value);
					this.SendPropertyChanging();
					this._Section_A = value;
					this.SendPropertyChanged("Section_A");
					this.OnSection_AChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_B", DbType="SmallInt")]
		public System.Nullable<short> Section_B
		{
			get
			{
				return this._Section_B;
			}
			set
			{
				if ((this._Section_B != value))
				{
					this.OnSection_BChanging(value);
					this.SendPropertyChanging();
					this._Section_B = value;
					this.SendPropertyChanged("Section_B");
					this.OnSection_BChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pin_Code", DbType="VarChar(10)")]
		public string Pin_Code
		{
			get
			{
				return this._Pin_Code;
			}
			set
			{
				if ((this._Pin_Code != value))
				{
					this.OnPin_CodeChanging(value);
					this.SendPropertyChanging();
					this._Pin_Code = value;
					this.SendPropertyChanged("Pin_Code");
					this.OnPin_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReg", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateReg
		{
			get
			{
				return this._DateReg;
			}
			set
			{
				if ((this._DateReg != value))
				{
					this.OnDateRegChanging(value);
					this.SendPropertyChanging();
					this._DateReg = value;
					this.SendPropertyChanged("DateReg");
					this.OnDateRegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monthOf", DbType="Int")]
		public System.Nullable<int> monthOf
		{
			get
			{
				return this._monthOf;
			}
			set
			{
				if ((this._monthOf != value))
				{
					this.OnmonthOfChanging(value);
					this.SendPropertyChanging();
					this._monthOf = value;
					this.SendPropertyChanged("monthOf");
					this.OnmonthOfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yearOf", DbType="BigInt")]
		public System.Nullable<long> yearOf
		{
			get
			{
				return this._yearOf;
			}
			set
			{
				if ((this._yearOf != value))
				{
					this.OnyearOfChanging(value);
					this.SendPropertyChanging();
					this._yearOf = value;
					this.SendPropertyChanged("yearOf");
					this.OnyearOfChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SMS_Reply")]
	public partial class SMS_Reply : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Tagged_ID;
		
		private string _Message;
		
		private string _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTagged_IDChanging(string value);
    partial void OnTagged_IDChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public SMS_Reply()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tagged_ID", DbType="VarChar(20)")]
		public string Tagged_ID
		{
			get
			{
				return this._Tagged_ID;
			}
			set
			{
				if ((this._Tagged_ID != value))
				{
					this.OnTagged_IDChanging(value);
					this.SendPropertyChanging();
					this._Tagged_ID = value;
					this.SendPropertyChanged("Tagged_ID");
					this.OnTagged_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(200)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SMS_TransferFundReport")]
	public partial class SMS_TransferFundReport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _ReferenceNo;
		
		private string _Sender;
		
		private string _Receiver;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<System.DateTime> _DateTransfered;
		
		private System.Nullable<bool> _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnReferenceNoChanging(string value);
    partial void OnReferenceNoChanged();
    partial void OnSenderChanging(string value);
    partial void OnSenderChanged();
    partial void OnReceiverChanging(string value);
    partial void OnReceiverChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnDateTransferedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateTransferedChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public SMS_TransferFundReport()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceNo", DbType="VarChar(10)")]
		public string ReferenceNo
		{
			get
			{
				return this._ReferenceNo;
			}
			set
			{
				if ((this._ReferenceNo != value))
				{
					this.OnReferenceNoChanging(value);
					this.SendPropertyChanging();
					this._ReferenceNo = value;
					this.SendPropertyChanged("ReferenceNo");
					this.OnReferenceNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sender", DbType="VarChar(11)")]
		public string Sender
		{
			get
			{
				return this._Sender;
			}
			set
			{
				if ((this._Sender != value))
				{
					this.OnSenderChanging(value);
					this.SendPropertyChanging();
					this._Sender = value;
					this.SendPropertyChanged("Sender");
					this.OnSenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Receiver", DbType="VarChar(11)")]
		public string Receiver
		{
			get
			{
				return this._Receiver;
			}
			set
			{
				if ((this._Receiver != value))
				{
					this.OnReceiverChanging(value);
					this.SendPropertyChanging();
					this._Receiver = value;
					this.SendPropertyChanged("Receiver");
					this.OnReceiverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTransfered", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTransfered
		{
			get
			{
				return this._DateTransfered;
			}
			set
			{
				if ((this._DateTransfered != value))
				{
					this.OnDateTransferedChanging(value);
					this.SendPropertyChanging();
					this._DateTransfered = value;
					this.SendPropertyChanged("DateTransfered");
					this.OnDateTransferedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SMS_eMoney")]
	public partial class SMS_eMoney : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _Account;
		
		private decimal _Amount;
		
		private bool _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnAccountChanging(string value);
    partial void OnAccountChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    partial void OnStatusChanging(bool value);
    partial void OnStatusChanged();
    #endregion
		
		public SMS_eMoney()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this.OnAccountChanging(value);
					this.SendPropertyChanging();
					this._Account = value;
					this.SendPropertyChanged("Account");
					this.OnAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2) NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SMS_WeatherForecast")]
	public partial class SMS_WeatherForecast : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _city;
		
		private string _weather_code;
		
		private System.Nullable<bool> _selected;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void Onweather_codeChanging(string value);
    partial void Onweather_codeChanged();
    partial void OnselectedChanging(System.Nullable<bool> value);
    partial void OnselectedChanged();
    #endregion
		
		public SMS_WeatherForecast()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(100)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weather_code", DbType="VarChar(20)")]
		public string weather_code
		{
			get
			{
				return this._weather_code;
			}
			set
			{
				if ((this._weather_code != value))
				{
					this.Onweather_codeChanging(value);
					this.SendPropertyChanging();
					this._weather_code = value;
					this.SendPropertyChanged("weather_code");
					this.Onweather_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_selected", DbType="Bit")]
		public System.Nullable<bool> selected
		{
			get
			{
				return this._selected;
			}
			set
			{
				if ((this._selected != value))
				{
					this.OnselectedChanging(value);
					this.SendPropertyChanging();
					this._selected = value;
					this.SendPropertyChanged("selected");
					this.OnselectedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SMS_BayanihanSum")]
	public partial class SMS_BayanihanSum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _bayanihan_ref;
		
		private System.Nullable<int> _played;
		
		private System.Nullable<decimal> _donation;
		
		private string _combination_no_win;
		
		private System.Nullable<System.DateTime> _open_started;
		
		private System.Nullable<System.DateTime> _closing_time;
		
		private string _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onbayanihan_refChanging(string value);
    partial void Onbayanihan_refChanged();
    partial void OnplayedChanging(System.Nullable<int> value);
    partial void OnplayedChanged();
    partial void OndonationChanging(System.Nullable<decimal> value);
    partial void OndonationChanged();
    partial void Oncombination_no_winChanging(string value);
    partial void Oncombination_no_winChanged();
    partial void Onopen_startedChanging(System.Nullable<System.DateTime> value);
    partial void Onopen_startedChanged();
    partial void Onclosing_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onclosing_timeChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public SMS_BayanihanSum()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bayanihan_ref", DbType="VarChar(50)")]
		public string bayanihan_ref
		{
			get
			{
				return this._bayanihan_ref;
			}
			set
			{
				if ((this._bayanihan_ref != value))
				{
					this.Onbayanihan_refChanging(value);
					this.SendPropertyChanging();
					this._bayanihan_ref = value;
					this.SendPropertyChanged("bayanihan_ref");
					this.Onbayanihan_refChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_played", DbType="Int")]
		public System.Nullable<int> played
		{
			get
			{
				return this._played;
			}
			set
			{
				if ((this._played != value))
				{
					this.OnplayedChanging(value);
					this.SendPropertyChanging();
					this._played = value;
					this.SendPropertyChanged("played");
					this.OnplayedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donation", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> donation
		{
			get
			{
				return this._donation;
			}
			set
			{
				if ((this._donation != value))
				{
					this.OndonationChanging(value);
					this.SendPropertyChanging();
					this._donation = value;
					this.SendPropertyChanged("donation");
					this.OndonationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_combination_no_win", DbType="VarChar(50)")]
		public string combination_no_win
		{
			get
			{
				return this._combination_no_win;
			}
			set
			{
				if ((this._combination_no_win != value))
				{
					this.Oncombination_no_winChanging(value);
					this.SendPropertyChanging();
					this._combination_no_win = value;
					this.SendPropertyChanged("combination_no_win");
					this.Oncombination_no_winChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_open_started", DbType="DateTime")]
		public System.Nullable<System.DateTime> open_started
		{
			get
			{
				return this._open_started;
			}
			set
			{
				if ((this._open_started != value))
				{
					this.Onopen_startedChanging(value);
					this.SendPropertyChanging();
					this._open_started = value;
					this.SendPropertyChanged("open_started");
					this.Onopen_startedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_closing_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> closing_time
		{
			get
			{
				return this._closing_time;
			}
			set
			{
				if ((this._closing_time != value))
				{
					this.Onclosing_timeChanging(value);
					this.SendPropertyChanging();
					this._closing_time = value;
					this.SendPropertyChanged("closing_time");
					this.Onclosing_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(100)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SMS_Bayanihan")]
	public partial class SMS_Bayanihan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<long> _Id;
		
		private string _bayanihan_ref;
		
		private string _donator;
		
		private string _combination;
		
		private System.Nullable<decimal> _donation;
		
		private System.Nullable<System.DateTime> _date_danated;
		
		private string _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Nullable<long> value);
    partial void OnIdChanged();
    partial void Onbayanihan_refChanging(string value);
    partial void Onbayanihan_refChanged();
    partial void OndonatorChanging(string value);
    partial void OndonatorChanged();
    partial void OncombinationChanging(string value);
    partial void OncombinationChanged();
    partial void OndonationChanging(System.Nullable<decimal> value);
    partial void OndonationChanged();
    partial void Ondate_danatedChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_danatedChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public SMS_Bayanihan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnUpdate, DbType="BigInt", IsPrimaryKey=true)]
		public System.Nullable<long> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bayanihan_ref", DbType="VarChar(50)")]
		public string bayanihan_ref
		{
			get
			{
				return this._bayanihan_ref;
			}
			set
			{
				if ((this._bayanihan_ref != value))
				{
					this.Onbayanihan_refChanging(value);
					this.SendPropertyChanging();
					this._bayanihan_ref = value;
					this.SendPropertyChanged("bayanihan_ref");
					this.Onbayanihan_refChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donator", DbType="VarChar(11)")]
		public string donator
		{
			get
			{
				return this._donator;
			}
			set
			{
				if ((this._donator != value))
				{
					this.OndonatorChanging(value);
					this.SendPropertyChanging();
					this._donator = value;
					this.SendPropertyChanged("donator");
					this.OndonatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_combination", DbType="VarChar(10)")]
		public string combination
		{
			get
			{
				return this._combination;
			}
			set
			{
				if ((this._combination != value))
				{
					this.OncombinationChanging(value);
					this.SendPropertyChanging();
					this._combination = value;
					this.SendPropertyChanged("combination");
					this.OncombinationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donation", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> donation
		{
			get
			{
				return this._donation;
			}
			set
			{
				if ((this._donation != value))
				{
					this.OndonationChanging(value);
					this.SendPropertyChanging();
					this._donation = value;
					this.SendPropertyChanged("donation");
					this.OndonationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_danated", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_danated
		{
			get
			{
				return this._date_danated;
			}
			set
			{
				if ((this._date_danated != value))
				{
					this.Ondate_danatedChanging(value);
					this.SendPropertyChanging();
					this._date_danated = value;
					this.SendPropertyChanged("date_danated");
					this.Ondate_danatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(100)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
